services:
  api:
    build:
      context: .
      target: dev
    container_name: assettracker-api
    env_file:
      - .env
    volumes:
      - .:/app
      - ~/.m2:/root/.m2
    depends_on:
      - db
    ports:
      - "8080:8080"
  db:
    image: postgres:latest
    restart: always
    container_name: assettracker-db
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
  pgadmin:
    image: dpage/pgadmin4:9.10.0
    restart: always
    container_name: assettracker-pgadmin4
    volumes:
      - pgadmin:/var/lib/pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PG_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PG_PASSWORD}
    ports:
      - "5051:80"
    depends_on:
      - db
volumes:
  db:
  pgadmin: